---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - Товары в корзине должны сохраняться на протяжении всей сессии в бразузере
  - Важно безопасно интегрировать систему оплаты
  - Пользователь должен иметь возможность удалить товар из корзины
  - Пользователь должен иметь возможность изменять количество добавляемого товара
  - Пользователь должен иметь возможность видеть итоговую сумму заказа в корзине
  - При импользовании чек-бокса должна быть возможность выделить несколько брэндов
  - При использовании приложения на различных устройствах не должно быть ошибок верстки
  - Все доступные бренды должны быть представлены в разделе "Производитель"
  - У пользователя должна быть возможность отменить выбор категории в списке "Категории"
  - Должна существовать общая фильтрация товаров во всем магазине
  - Если в онлайн магазине присутствует несколько страниц с разными категориями товаров, то у покупателя должна быть возможность видеть полную карту сайта
  - Страница товара должна содержать название товара
  - Страница товара должна содержать рейтинг товара
  - Страница товара должна содержать цену товара со скидкой и без скидки
  - В каталоге у товара должны быть название, рейтинг, цена без скидки и со скидкой
  - Пользователь должен иметь возможность продолжить выбор товаров из каталога после добавления какого-либо товара в корзину
  - Товары на каждой странице магазина должны отображаться в фиксированном порядке при переключении между страницами
  - У пользователя должна быть возможно отменить выбранную фильтрацию
  - Разбиение товаров по страницам должно быть логичным (одна страница - одежда, другая страница - обувь, и т.д.)
  - В мобильной версии приложения фильтры должны быть в отдельной вкладке ради удобства использования
  - После успешного оформления заказа, пользователь должен быть перенаправлен на страницу оплаты
